# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f66a1cd1690433eb61446dc8a9a8aad211440da833aeeca026b0c4df6eed22bd927b51d05e98f0d5a810000d7c745da91cc7e27b0b765f1e1435157458d54b1

test:
  secret_key_base: 5fc0127e2dfd01e58ec74182705dbb693f945ad99a3f6b9a2740e797ff8ffe8eaef0bae0be9365e5992cc96ba7c57dc097f587c3dd108e490defadefb411b334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
